[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contracts = "2ZcYtu6b6P6rKXittUPvncSaLRuEtNSoqeRc9RVCHY4q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kostyamospan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
